QDK_VERSION=2.3.7

diff --git a/QDK/shared/bin/qbuild b/QDK/shared/bin/qbuild
--- a/QDK/shared/bin/qbuild
+++ b/QDK/shared/bin/qbuild
@@ -159,8 +159,13 @@ s/^offset.*/&;/p
 	echo "$(eval $offset_command)"
 }
 
+# Code signing server info
+readonly DEFAULT_QNAP_CODE_SIGNING_SERVER_IP="172.17.21.68"
+readonly DEFAULT_QNAP_CODE_SIGNING_SERVER_PORT="5000"
+
 # Supported data types in the QDK area.
 readonly QDK_AREA_SIGNATURE=1
+readonly QDK_AREA_CODE_SIGNING=254
 readonly QDK_AREA_EOF=255
 
 # Length of QDK tag that is added to the front of the QDK area.
@@ -240,6 +245,30 @@ get_signature_len(){
 	[ -f $qpkg ] || err_msg "$qpkg: no such file"
 	local qdk_pos=
 	qdk_pos="$(get_qdk_area_data_pos $QDK_AREA_SIGNATURE $qpkg)" || return 1
+	qdk_pos="$(($qdk_pos + $QDK_AREA_DATA_TYPE_LEN))"
+
+	echo "$(network_order_32bit $qdk_pos $qpkg)"
+}
+
+# Retrieve location of code signing data (if found)
+get_code_signing_pos(){
+	[ -n "$1" ] || err_msg "internal error: get_code_signing_pos called with no argument"
+	local qpkg="$1"
+	[ -f $qpkg ] || err_msg "$qpkg: no such file"
+	local qdk_pos=
+	qdk_pos="$(get_qdk_area_data_pos $QDK_AREA_CODE_SIGNING $qpkg)" || return 1
+
+	# The code signing data is located after the data type and size data.
+	echo "$(($qdk_pos + $QDK_AREA_DATA_TYPE_LEN + $QDK_AREA_DATA_SIZE_LEN))"
+}
+
+# Retrieve size of code signing data (if found)
+get_code_signing_len(){
+	[ -n "$1" ] || err_msg "internal error: get_code_signing_len called with no argument"
+	local qpkg="$1"
+	[ -f $qpkg ] || err_msg "$qpkg: no such file"
+	local qdk_pos=
+	qdk_pos="$(get_qdk_area_data_pos $QDK_AREA_CODE_SIGNING $qpkg)" || return 1
 	qdk_pos="$(($qdk_pos + $QDK_AREA_DATA_TYPE_LEN))"
 
 	echo "$(network_order_32bit $qdk_pos $qpkg)"
@@ -476,6 +505,16 @@ perform_data_package_adaptor(){
 	fi
 }
 
+# Code signing related routines
+do_code_signing(){
+	local build_dir="${1:-build.$$}"
+	msg "Creating code signing data..."
+	[ -z "$QNAP_CODE_SIGNING_CSV" ] && QNAP_CODE_SIGNING_CSV="build_sign.csv"
+	[ -z "$QNAP_CODE_SIGNING_SERVER_IP" ] && QNAP_CODE_SIGNING_SERVER_IP=$DEFAULT_QNAP_CODE_SIGNING_SERVER_IP
+	[ -z "$QNAP_CODE_SIGNING_SERVER_PORT" ] && QNAP_CODE_SIGNING_SERVER_PORT=$DEFAULT_QNAP_CODE_SIGNING_SERVER_PORT
+	python "${QDK_SCRIPTS_DIR}/codesigning_qpkg.py" cert="${QDK_SCRIPTS_DIR}/codesigning_cert.pem" cwd="`pwd`" buildpath=$build_dir csv="${QNAP_CODE_SIGNING_CSV}" server=${QNAP_CODE_SIGNING_SERVER_IP}:${QNAP_CODE_SIGNING_SERVER_PORT}  2>&1 | tee -a code_signing.log
+}
+
 # Create data package for distribution.
 create_data_package(){
 	local arch_msg="${1:+ for $1}"
@@ -499,6 +538,11 @@ create_data_package(){
 	cd build.$$
 	perform_data_package_adaptor
 	cd - > /dev/null 2>&1
+
+	find . -type d -name '.qcodesigning' | xargs rm -rf
+	if [ "x${QNAP_CODE_SIGNING}" = "x1" ]; then
+		do_code_signing
+	fi
 
 	verbose_msg "Creating compressed tar archive..."
 	case "$QDK_COMPRESS_METHOD" in
@@ -836,6 +880,18 @@ add_qdk_area_signature(){
 	/bin/cat $data >> $qpkg
 }
 
+# Add code signing data to QDK area.
+add_qdk_area_code_signing(){
+	[ -n "$1" ] || err_msg "internal error: add_qdk_area_code_signing called with no argument"
+	local data="$1"
+	local qpkg="${2:-$QDK_QPKG_FILE}"
+	local size="$(/bin/ls -l $data | $CMD_AWK '{ print $5 }')"
+	add_qdk_area_data_type $QDK_AREA_CODE_SIGNING $qpkg
+	add_qdk_area_data_size $size $qpkg
+	debug_msg "Data: $data"
+	/bin/cat $data >> $qpkg
+}
+
 # Add end tag to QDK area.
 add_qdk_area_end(){
 	add_qdk_area_data_type $QDK_AREA_EOF $1
@@ -844,7 +900,23 @@ add_qdk_area_end(){
 
 # Add signature to QPKG.
 add_qpkg_signature(){
-	if [ "$QDK_SIGN" = "TRUE" ]; then
+	if [ "x${QNAP_CODE_SIGNING}" = "x1" ]; then
+		verbose_msg "Adding code signing data..."
+		[ -z "$QNAP_CODE_SIGNING_SERVER_IP" ] && QNAP_CODE_SIGNING_SERVER_IP=$DEFAULT_QNAP_CODE_SIGNING_SERVER_IP
+		[ -z "$QNAP_CODE_SIGNING_SERVER_PORT" ] && QNAP_CODE_SIGNING_SERVER_PORT=$DEFAULT_QNAP_CODE_SIGNING_SERVER_PORT
+		openssl dgst -sha1 -binary "${QDK_QPKG_FILE}" > "${QDK_QPKG_FILE}.sha"
+		python "${QDK_SCRIPTS_DIR}/codesigning_qpkg_cms.py" cert="${QDK_SCRIPTS_DIR}/codesigning_cert.pem" cwd="`pwd`" server=${QNAP_CODE_SIGNING_SERVER_IP}:${QNAP_CODE_SIGNING_SERVER_PORT} in="${QDK_QPKG_FILE}.sha" out="${QDK_QPKG_FILE}.msg" 2>&1 | tee -a code_signing.log
+		/bin/rm ${QDK_QPKG_FILE}.sha
+		if [ -f "${QDK_QPKG_FILE}.msg" ]; then
+			add_qdk_area_begin
+			add_qdk_area_code_signing ${QDK_QPKG_FILE}.msg
+			add_qdk_area_end
+			/bin/rm ${QDK_QPKG_FILE}.msg
+		else
+			warn_msg "$QDK_QPKG_FILE: no code signing data added"
+		fi
+
+	elif [ "$QDK_SIGN" = "TRUE" ]; then
 		verbose_msg "Adding signature..."
 
 		case "$QDK_SIGNATURE" in
@@ -929,6 +1001,10 @@ create_qpkg(){
 	add_qpkg_signature
 	add_qpkg_tail
 	add_qpkg_encryption
+
+	if [ "x${QNAP_CODE_SIGNING}" = "x1" ]; then
+		verify_code_signing ${QDK_QPKG_FILE}
+	fi
 
 	debug_msg "Copying $QDK_QPKG_FILE to $QDK_BUILD_DIR"
 	/bin/cp -fp $QDK_QPKG_FILE $QDK_BUILD_DIR
@@ -1171,12 +1247,6 @@ cleanup_after_build(){
 	call_teardown
 }
 
-# Code signing related routines
-do_code_signing(){
-	msg "Creating code signing data..."
-	python "${QDK_SCRIPTS_DIR}/codesigning_qdk.py" cert="${QDK_SCRIPTS_DIR}/codesigning_cert.pem" cwd="`pwd`" csv="${QNAP_CODE_SIGNING_CSV}" server=${QNAP_CODE_SIGNING_SERVER_IP}:${QNAP_CODE_SIGNING_SERVER_PORT}  2>&1 | tee -a code_signing.log
-}
-
 # Main build function.
 build_qpkg(){
 	# All build operation should be run in the QDK_ROOT_DIR directory (current
@@ -1184,11 +1254,6 @@ build_qpkg(){
 	cd "${QDK_ROOT_DIR:-.}" 2>/dev/null || err_msg "$QDK_ROOT_DIR: no such directory"
 
 	initialize_build_environment
-
-	find . -type d -name '.qcodesigning' | xargs rm -rf
-	if [ "x${QNAP_CODE_SIGNING}" = "x1" ]; then
-		do_code_signing
-	fi
 
 	if [ -n "$QDK_BUILD_ARCH" ]; then
 		traverse_and_build
@@ -1209,7 +1274,6 @@ create_env(){
 	/bin/mkdir -m 755 -p "$qpkg_name" || err_msg "$qpkg_name: failed to create directory"
 
 	/bin/cp -pfr "${QDK_TEMPLATE_DIR}"/* "$qpkg_name"
-	find "$qpkg_name" -name .svn | xargs rm -rf
 
 	local qpkg_cfg="${qpkg_name}/qpkg.cfg"
 	edit_qpkg_config QPKG_AUTHOR "$(/usr/bin/whoami)" "$qpkg_cfg"
@@ -1236,7 +1300,7 @@ extract_qpkg(){
 	local dd_quiet=
 	local tar_quiet=
 	is_quiet && tar_quiet=">/dev/null"
-	is_verbose|| dd_quiet="2>/dev/null"
+	is_verbose || dd_quiet="2>/dev/null"
 	local extract_command="$(/bin/sed -n "1,/^exit 1/{
 s!if=\"\${0}\" \(.* -C\) .*!$dd_quiet if=$qpkg \1 $dir $tar_quiet;!p
 s!if=\"\${0}\" \(.* of.*\) ||.*!$dd_quiet if=$qpkg \1 $dd_quiet;!p
@@ -1430,6 +1494,145 @@ add_qdk_definitions(){
 	fi
 }
 
+# Add code signing data into QPKG
+add_code_signing(){
+	[ -n "$1" ] || err_msg "internal error: add_code_signing called with no argument"
+	local qpkg="$1"
+	local code_signing_cfg="${2:-"`pwd`/qpkg.cfg"}"
+	[ -f $qpkg ] || err_msg "$qpkg: no such file"
+	[ -f $code_signing_cfg ] || err_msg "$code_signing_cfg: no such file"
+
+	verbose_msg "Find and remove any existing signature..."
+	local data_size=
+	if data_size=$(get_content_size $qpkg); then
+		local sign_pos=
+		if sign_pos=$(get_signature_pos $qpkg); then
+			local sign_len=$(get_signature_len $qpkg)
+			debug_msg "Signature located at position $sign_pos with size $sign_len"
+			verbose_msg "Existing signature removed"
+		fi
+
+		local code_signing_pos=
+		if code_signing_pos=$(get_code_signing_pos $qpkg); then
+			local code_signing_len=$(get_code_signing_len $qpkg)
+			debug_msg "Code signing data located at position $code_signing_pos with size $code_signing_len"
+			verbose_msg "Existing code signing data removed"
+		fi
+	fi
+	[ -n "$data_size" ] || err_msg "$qpkg: not QDK 2.0 or later"
+
+	verbose_msg "Generate and add code signing data..."
+
+	# Source the configuration file to make all its fields available.
+	. "$code_signing_cfg" || err_msg "$code_signing_cfg: corrupt configuration file"
+	[ -n "$QPKG_NAME" ] || err_msg "$code_signing_cfg: QPKG_NAME not provided"
+	[ -n "$QPKG_VER" ] || err_msg "$code_signing_cfg: QPKG_VER not provided"
+	[ -z "$QNAP_CODE_SIGNING_SERVER_IP" ] && QNAP_CODE_SIGNING_SERVER_IP=$DEFAULT_QNAP_CODE_SIGNING_SERVER_IP
+	[ -z "$QNAP_CODE_SIGNING_SERVER_PORT" ] && QNAP_CODE_SIGNING_SERVER_PORT=$DEFAULT_QNAP_CODE_SIGNING_SERVER_PORT
+
+	dd_cmd="/bin/dd if=$qpkg bs=$data_size count=1 2>/dev/null > ${qpkg}.$$"
+	debug_msg "$dd_cmd"
+	eval "$dd_cmd"
+
+	# Send qpkg digest to server
+	openssl dgst -sha1 -binary "${qpkg}.$$" > "${qpkg}.sha"
+	python "${QDK_SCRIPTS_DIR}/codesigning_qpkg_cms.py" cert="${QDK_SCRIPTS_DIR}/codesigning_cert.pem" server=${QNAP_CODE_SIGNING_SERVER_IP}:${QNAP_CODE_SIGNING_SERVER_PORT} qpkgname=${QPKG_NAME} version=${QPKG_VER} in="${qpkg}.sha" out="${qpkg}.msg" 2>&1 | tee -a code_signing.log
+	/bin/rm ${qpkg}.sha
+
+	# Add code signing data into qpkg
+	if [ -f "${qpkg}.msg" ]; then
+		add_qdk_area_begin ${qpkg}.$$
+		add_qdk_area_code_signing ${qpkg}.msg ${qpkg}.$$
+		add_qdk_area_end ${qpkg}.$$
+		/bin/rm ${qpkg}.msg
+	else
+		/bin/rm ${qpkg}.$$
+		err_msg "$qpkg: no code signing data added"
+	fi
+
+	verbose_msg "Add tail data..."
+	printf "$(/usr/bin/tail -c$TAIL_DATA_LEN $qpkg)" >> ${qpkg}.$$
+	verbose_msg "Adding QPKG checksum: $(/sbin/qpkg --encrypt ${qpkg}.$$)"
+	/bin/mv ${qpkg}.$$ $qpkg
+}
+
+# Verify code signing data in a QPKG
+verify_code_signing(){
+	[ -n "$1" ] || err_msg "internal error: verify_code_signing called with no argument"
+	local qpkg="$1"
+	local code_signing_cfg="${2:-"`pwd`/qpkg.cfg"}"
+	[ -f $qpkg ] || err_msg "$qpkg: no such file"
+	[ -f $code_signing_cfg ] || err_msg "$code_signing_cfg: no such file"
+
+	data_size=$(get_qdk_area_pos $qpkg) || err_msg "verification failed: cannot find qdk area"
+	code_signing_pos=$(get_code_signing_pos $qpkg) || \
+		err_msg "verification failed: cannot find code signing data position"
+	code_signing_len=$(get_code_signing_len $qpkg) || \
+		err_msg "verification failed: cannot find code signing data length"
+
+	# Source the configuration file to make all its fields available.
+	. "$code_signing_cfg" || err_msg "$code_signing_cfg: corrupt configuration file"
+	[ -z "$QNAP_CODE_SIGNING_SERVER_IP" ] && QNAP_CODE_SIGNING_SERVER_IP=$DEFAULT_QNAP_CODE_SIGNING_SERVER_IP
+	[ -z "$QNAP_CODE_SIGNING_SERVER_PORT" ] && QNAP_CODE_SIGNING_SERVER_PORT=$DEFAULT_QNAP_CODE_SIGNING_SERVER_PORT
+
+	# Get ca cert
+	ca_cert_file="${qpkg}.ca"
+	curl_cmd="curl -k -X GET -d 'token=${QNAP_CODESIGNING_TOKEN}' \
+		https://${QNAP_CODE_SIGNING_SERVER_IP}:${QNAP_CODE_SIGNING_SERVER_PORT}/keys/qnaproot \
+		2>/dev/null"
+	output="$(eval $curl_cmd)" || err_msg "failed to connect to code signing server"
+	server_err=$(echo $output | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["error"]')
+	if [ $server_err -ne 0 ]; then
+		server_msg=$(echo $output | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["msg"]')
+		err_msg "error from code signing server: $server_msg"
+	fi
+	echo $output | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["certificate"]["pem"]' > $ca_cert_file
+
+	# Get ca cert (3rd party)
+	ca_cert3_file="${qpkg}.ca3"
+	curl_cmd="curl -k -X GET -d 'token=${QNAP_CODESIGNING_TOKEN}&third_party=true' \
+		https://${QNAP_CODE_SIGNING_SERVER_IP}:${QNAP_CODE_SIGNING_SERVER_PORT}/keys/qnaproot \
+		2>/dev/null"
+	output="$(eval $curl_cmd)" || err_msg "failed to connect to code signing server"
+	server_err=$(echo $output | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["error"]')
+	if [ $server_err -ne 0 ]; then
+		server_msg=$(echo $output | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["msg"]')
+		err_msg "error from code signing server: $server_msg"
+	fi
+	echo $output | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["certificate"]["pem"]' > $ca_cert3_file
+
+	# Verify
+	qpkg_data_file="${qpkg}.data"
+	dgst_file="${qpkg}.dgst"
+	signature_file="${qpkg}.msg"
+	verify_dgst_file="${qpkg}.verify"
+	/bin/dd if=$qpkg bs=$data_size count=1 2>/dev/null > $qpkg_data_file
+	openssl dgst -sha1 -binary $qpkg_data_file 2>/dev/null > $dgst_file
+	/bin/dd if=$qpkg bs=1 skip=$code_signing_pos count=$code_signing_len 2>/dev/null > $signature_file
+
+	# Verify using non-3rd party CA
+	openssl cms -verify -in $signature_file -CAfile $ca_cert_file 2>/dev/null > $verify_dgst_file
+	/bin/cmp $dgst_file $verify_dgst_file 2>/dev/null
+	if [ $? -eq 0 ]; then
+		msg "Verification successful"
+	else
+		# Verify using 3rd party CA
+		openssl cms -verify -in $signature_file -CAfile $ca_cert3_file 2>/dev/null > $verify_dgst_file
+		/bin/cmp $dgst_file $verify_dgst_file 2>/dev/null
+		if [ $? -eq 0 ]; then
+			msg "Verification successful (3rd party qpkg)"
+		else
+			msg "Verification failed"
+		fi
+	fi
+	/bin/rm $qpkg_data_file
+	/bin/rm $dgst_file
+	/bin/rm $signature_file
+	/bin/rm $verify_dgst_file
+	/bin/rm $ca_cert_file
+	/bin/rm $ca_cert3_file
+}
+
 usage(){
 	/bin/cat <<EOF
 usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--section SECTION]
@@ -1440,6 +1643,8 @@ usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--
 	[--gzip|--bzip2|--7zip] [--sign] [--gpg-name ID] [--verify QPKG]
 	[--add-sign QPKG] [--import-key KEY] [--remove-key ID] [--list-keys]
 	[--query OPTION QPKG] [-v|--verbose] [-q|--quiet] [--strict]
+	[--add-code-signing QPKG] [--verify-code-signing QPKG]
+	[--code-signing-cfg CODE_SIGNING_CFG]
 	[-?|-h|--help] [--usage] [-V|--version]
 EOF
 	exit 0
@@ -1454,8 +1659,10 @@ usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--
 	[--pre-build SCRIPT] [--post-build SCRIPT] [--exclude PATTERN]
 	[--exclude-from FILE] [--gzip|--bzip2|--7zip] [--sign] [--gpg-name ID]
 	[--verify QPKG] [--add-sign QPKG] [--import-key KEY] [--remove-key ID]
-	[--list-keys] [--query OPTION QPKG] [-v|--verbose] [-q|--quiet]
-	[--strict] [-?|-h|--help] [--usage] [-V|--version]
+	[--list-keys] [--query OPTION QPKG] [-v|--verbose] [-q|--quiet] [--strict]
+	[--add-code-signing QPKG] [--verify-code-signing QPKG]
+	[--code-signing-cfg CODE_SIGNING_CFG]
+	[-?|-h|--help] [--usage] [-V|--version]
 
 -s
 --section SECTION
@@ -1547,6 +1754,16 @@ usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--
 	Show keys in public keyring.
 --remove-key ID
 	Remove key with specified ID from public keyring.
+--add-code-signing QPKG CODE_SIGNING_CFG
+	Add code signing data into QPKG. By default configuration file 'qpkg.cfg' is used
+	(This option is internal use only)
+--verify-code-signing QPKG
+	Verify code signing data in the QPKG. By default configuration file 'qpkg.cfg' is used
+	(This option is internal use only)
+--code-signing-cfg CODE_SIGNING_CFG
+	The configuration file for --add-code-signing and --verify-code-signing
+	(This option is internal use only)
+
 -?
 -h
 --help
@@ -1601,6 +1818,9 @@ main(){
 	local qbuild_add_sign_file=
 	local qbuild_sign=
 	local qbuild_list_keys=
+	local qbuild_add_code_signing_file=
+	local qbuild_verify_code_signing_file=
+	local qbuild_code_signing_cfg_file=
 	while  [ $# -gt 0 ]
 	do
 		case "$1" in
@@ -1714,6 +1934,21 @@ main(){
 				[ -n "$qbuild_query_qpkg" ] || err_msg "--query: missing argument"
 				shift
 				;;
+			--add-code-signing)
+				qbuild_add_code_signing_file="$2"
+				[ -n "$qbuild_add_code_signing_file" ] || err_msg "--add-code-signing: no qpkg file"
+				shift
+				;;
+			--verify-code-signing)
+				qbuild_verify_code_signing_file="$2"
+				[ -n "$qbuild_verify_code_signing_file" ] || err_msg "--verify-code-signing: no qpkg file"
+				shift
+				;;
+			--code-signing-cfg)
+				qbuild_code_signing_cfg_file="$2"
+				[ -n "$qbuild_code_signing_cfg_file" ] || err_msg "--code-signing-cfg: no cfg file"
+				shift
+				;;
 			-*)		qbuild_usage=TRUE ;;
 		esac
 		shift
@@ -1764,6 +1999,14 @@ main(){
 		list_keys
 	elif [ -n "$qbuild_query_qpkg" ]; then
 		query_qpkg "$qbuild_query_option" "$qbuild_query_qpkg"
+	elif [ -n "$qbuild_add_code_signing_file" ] && [ -n "$qbuild_code_signing_cfg_file" ]; then
+		add_code_signing "$qbuild_add_code_signing_file" "$qbuild_code_signing_cfg_file"
+	elif [ -n "$qbuild_add_code_signing_file" ]; then
+		add_code_signing "$qbuild_add_code_signing_file"
+	elif [ -n "$qbuild_verify_code_signing_file" ] && [ -n "$qbuild_code_signing_cfg_file" ]; then
+		verify_code_signing "$qbuild_verify_code_signing_file" "$qbuild_code_signing_cfg_file"
+	elif [ -n "$qbuild_verify_code_signing_file" ]; then
+		verify_code_signing "$qbuild_verify_code_signing_file"
 	else
 		build_qpkg
 	fi
